name: "JFrog Credentials"
description: "Set JFrog credentials based on the JFrog URL"

on:
  workflow_call:
    inputs:
      JFROG_URL:
        description: "The JFrog URL"
        required: true
        type: string
    secrets:
      ARUBA_JFROG_USERNAME:
        description: "ARUBA JFrog Username"
        required: true
      ARUBA_JFROG_PASSWORD:
        description: "ARUBA JFrog Password"
        required: true
      CSS_JFROG_USERNAME:
        description: "CSS JFrog Username"
        required: true
      CSS_JFROG_PASSWORD:
        description: "CSS JFrog Password"
        required: true
      DEFAULT_JFROG_USERNAME:
        description: "Default JFrog Username"
        required: true
      DEFAULT_JFROG_PASSWORD:
        description: "Default JFrog Password"
        required: true


jobs:
  set-jfrog-credentials:
    runs-on: ubuntu-latest
    outputs:
      JFROG_USERNAME: ${{ steps.set-outputs.outputs.JFROG_USERNAME }}
      JFROG_PASSWORD: ${{ steps.set-outputs.outputs.JFROG_PASSWORD }}
    steps:
      - name: "Set JFrog Credentials"
        id: set-creds
        shell: bash
        run: |
          if [[ "${{ inputs.JFROG_URL }}" == "AURBA_URL" ]]; then
            echo "JFROG_USERNAME=${{ secrets.ARUBA_JFROG_USERNAME }}" >> $GITHUB_ENV
            echo "JFROG_PASSWORD=${{ secrets.ARUBA_JFROG_PASSWORD }}" >> $GITHUB_ENV
          elif [[ "${{ inputs.JFROG_URL }}" == "CSS_URL" ]]; then
            echo "JFROG_USERNAME=${{ secrets.CSS_JFROG_USERNAME }}" >> $GITHUB_ENV
            echo "JFROG_PASSWORD=${{ secrets.CSS_JFROG_PASSWORD }}" >> $GITHUB_ENV
          else
            echo "JFROG_USERNAME=${{ secrets.DEFAULT_JFROG_USERNAME }}" >> $GITHUB_ENV
            echo "JFROG_PASSWORD=${{ secrets.DEFAULT_JFROG_PASSWORD }}" >> $GITHUB_ENV
          fi

      - name: "Set Outputs"
        id: set-outputs
        shell: bash
        run: |
          echo "JFROG_USERNAME=$JFROG_USERNAME" >> $GITHUB_OUTPUT
          echo "JFROG_PASSWORD=$JFROG_PASSWORD" >> $GITHUB_OUTPUT
