name: "Set JFrog Credentials"
description: "Set JFrog credentials based on the JFrog URL"

inputs:
  JFROG_URL:
    description: "The JFrog URL"
    required: true
  ARUBA_JFROG_USERNAME:
    description: "ARUBA JFrog Username"
    required: true
  ARUBA_JFROG_PASSWORD:
    description: "ARUBA JFrog Password"
    required: true
  CSS_JFROG_USERNAME:
    description: "CSS JFrog Username"
    required: true
  CSS_JFROG_PASSWORD:
    description: "CSS JFrog Password"
    required: true
  DEFAULT_JFROG_USERNAME:
    description: "Default JFrog Username"
    required: true
  DEFAULT_JFROG_PASSWORD:
    description: "Default JFrog Password"
    required: true

outputs:
  JFROG_USERNAME:
    description: "JFrog Username"
  JFROG_PASSWORD:
    description: "JFrog Password"

runs:
  using: "composite"
  steps:
    - name: "Set JFrog Credentials"
      shell: bash
      run: |
        if [[ "${{ inputs.JFROG_URL }}" == "AURBA_URL" ]]; then
          echo "JFROG_USERNAME=${{ inputs.ARUBA_JFROG_USERNAME }}" >> $GITHUB_ENV
          echo "JFROG_PASSWORD=${{ inputs.ARUBA_JFROG_PASSWORD }}" >> $GITHUB_ENV
        elif [[ "${{ inputs.JFROG_URL }}" == "CSS_URL" ]]; then
          echo "JFROG_USERNAME=${{ inputs.CSS_JFROG_USERNAME }}" >> $GITHUB_ENV
          echo "JFROG_PASSWORD=${{ inputs.CSS_JFROG_PASSWORD }}" >> $GITHUB_ENV
        else
          echo "JFROG_USERNAME=${{ inputs.DEFAULT_JFROG_USERNAME }}" >> $GITHUB_ENV
          echo "JFROG_PASSWORD=${{ inputs.DEFAULT_JFROG_PASSWORD }}" >> $GITHUB_ENV
        fi

    - name: "Set Outputs"
      shell: bash
      run: |
        echo "JFROG_USERNAME=$JFROG_USERNAME" >> $GITHUB_OUTPUT
        echo "JFROG_PASSWORD=$JFROG_PASSWORD" >> $GITHUB_OUTPUT
