name: "JFrog Credentials"
description: "Set JFrog credentials based on the JFrog URL"

inputs:
  JFROG_URL:
    description: "The JFrog URL"
    required: true

outputs:
  JFROG_USERNAME:
    description: "JFrog Username"
  JFROG_PASSWORD:
    description: "JFrog Password"

runs:
  using: "composite"
  steps:
    - name: "Set JFrog Credentials"
      shell: bash
      run: |
        if [[ "${{ inputs.JFROG_URL }}" == "AURBA_URL" ]]; then
          echo "JFROG_USERNAME=${{ secrets.ARUBA_JFROG_USERNAME }}" >> $GITHUB_ENV
          echo "JFROG_PASSWORD=${{ secrets.ARUBA_JFROG_PASSWORD }}" >> $GITHUB_ENV
        elif [[ "${{ inputs.JFROG_URL }}" == "CSS_URL" ]]; then
          echo "JFROG_USERNAME=${{ secrets.CSS_JFROG_USERNAME }}" >> $GITHUB_ENV
          echo "JFROG_PASSWORD=${{ secrets.CSS_JFROG_PASSWORD }}" >> $GITHUB_ENV
        else
          echo "JFROG_USERNAME=${{ secrets.DEFAULT_JFROG_USERNAME }}" >> $GITHUB_ENV
          echo "JFROG_PASSWORD=${{ secrets.DEFAULT_JFROG_PASSWORD }}" >> $GITHUB_ENV
        fi
      env:
        GITHUB_ENV: $GITHUB_ENV
